# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DzUJraQBlthsdM3OlHFm1LN52LVSIZ0_
"""

import streamlit as st
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

import os
print(os.listdir())

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------

st.set_page_config(
    page_title="Hybrid Movie Recommendation System",
    layout="wide"
)

# --------------------------------------------------
# LOAD DATA
# --------------------------------------------------

@st.cache_data
def load_data():

    movies = pd.read_csv("movies.csv")
    ratings = pd.read_csv("ratings.csv")
    tags = pd.read_csv("tags.csv")

    movie_ratings = ratings.groupby(
        "movieId"
    )["rating"].mean().reset_index()

    movies_df = movies.merge(
        movie_ratings,
        on="movieId"
    )

    movies_df["year"] = movies_df[
        "title"
    ].str.extract(r"\((\d{4})\)")

    movies_df["year"] = pd.to_numeric(
        movies_df["year"],
        errors="coerce"
    )

    movie_tags = tags.groupby(
        "movieId"
    )["tag"].apply(
        lambda x: " ".join(
            x.astype(str)
        )
    ).reset_index()

    movies_nlp = movies_df.merge(
        movie_tags,
        on="movieId",
        how="left"
    )

    movies_nlp["tag"] = movies_nlp[
        "tag"
    ].fillna("")

    movies_nlp["text"] = (
        movies_nlp["genres"]
        + " "
        + movies_nlp["tag"]
    )

    return movies_nlp


movies_nlp = load_data()

# --------------------------------------------------
# NLP MODEL
# --------------------------------------------------

@st.cache_resource
def build_model(data):

    tfidf = TfidfVectorizer(
        stop_words="english"
    )

    tfidf_matrix = tfidf.fit_transform(
        data["text"]
    )

    return tfidf, tfidf_matrix


tfidf, tfidf_matrix = build_model(
    movies_nlp
)

# --------------------------------------------------
# SIDEBAR
# --------------------------------------------------

st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Select Page",
    [
        "Recommendation System",
        "Evaluation Dashboard"
    ]
)

# --------------------------------------------------
# PAGE 1
# --------------------------------------------------

if page == "Recommendation System":

    st.title(
        "🎬 Hybrid Movie Recommendation System"
    )

    st.markdown(
        """
        This system combines:

        - Rule-Based Filtering
        - TF-IDF NLP Processing
        - Cosine Similarity

        to generate movie recommendations.
        """
    )

    genre = st.selectbox(
        "Select Genre",
        [
            "Action",
            "Adventure",
            "Animation",
            "Comedy",
            "Crime",
            "Drama",
            "Fantasy",
            "Romance",
            "Sci-Fi",
            "Thriller"
        ]
    )

    rating = st.slider(
        "Minimum Rating",
        0.0,
        5.0,
        4.0
    )

    year = st.slider(
        "Minimum Release Year",
        1950,
        2025,
        2000
    )

    query = st.text_input(
        "Describe a movie you want",
        "family animation"
    )

    if st.button("Recommend Movies"):

        query_vector = tfidf.transform(
            [query]
        )

        similarity_scores = cosine_similarity(
            query_vector,
            tfidf_matrix
        ).flatten()

        movies_nlp[
            "similarity_score"
        ] = similarity_scores

        hybrid_results = movies_nlp[
            (movies_nlp["genres"].str.contains(
                genre,
                case=False,
                na=False
            ))
            &
            (movies_nlp["rating"] >= rating)
            &
            (movies_nlp["year"] >= year)
        ]

        hybrid_results = hybrid_results.sort_values(
            by=[
                "similarity_score",
                "rating"
            ],
            ascending=False
        )

        top10 = hybrid_results.head(10)

        st.subheader(
            "Top Recommendations"
        )

        st.dataframe(
            top10[
                [
                    "title",
                    "genres",
                    "rating",
                    "year",
                    "similarity_score"
                ]
            ]
        )

        st.subheader(
            "Recommendation Scores"
        )

        fig, ax = plt.subplots(
            figsize=(10,5)
        )

        ax.barh(
            top10["title"],
            top10["similarity_score"]
        )

        ax.set_xlabel(
            "Similarity Score"
        )

        ax.set_title(
            "Hybrid Recommendation Ranking"
        )

        ax.invert_yaxis()

        st.pyplot(fig)

# --------------------------------------------------
# PAGE 2
# --------------------------------------------------

if page == "Evaluation Dashboard":

    st.title(
        "📊 System Evaluation"
    )

    test_queries = [
        "family animation",
        "space adventure",
        "romantic drama",
        "action hero",
        "comedy movie"
    ]

    evaluation_results = []

    for query in test_queries:

        query_vector = tfidf.transform(
            [query]
        )

        scores = cosine_similarity(
            query_vector,
            tfidf_matrix
        ).flatten()

        evaluation_results.append({

            "Query":
            query,

            "Max Similarity":
            scores.max(),

            "Average Similarity":
            scores.mean(),

            "Recommendations Returned":
            10
        })

    evaluation_df = pd.DataFrame(
        evaluation_results
    )

    st.subheader(
        "Evaluation Results"
    )

    st.dataframe(
        evaluation_df
    )

    st.subheader(
        "Maximum Similarity Scores"
    )

    fig1, ax1 = plt.subplots(
        figsize=(8,4)
    )

    ax1.bar(
        evaluation_df["Query"],
        evaluation_df["Max Similarity"]
    )

    ax1.set_ylabel(
        "Score"
    )

    st.pyplot(fig1)

    st.subheader(
        "Average Similarity Scores"
    )

    fig2, ax2 = plt.subplots(
        figsize=(8,4)
    )

    ax2.bar(
        evaluation_df["Query"],
        evaluation_df["Average Similarity"]
    )

    ax2.set_ylabel(
        "Score"
    )

    st.pyplot(fig2)

    st.success(
        "Evaluation completed successfully."
    )

