# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DzUJraQBlthsdM3OlHFm1LN52LVSIZ0_
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")
tags = pd.read_csv("tags.csv")

# Average ratings

movie_ratings = ratings.groupby(
    "movieId"
)["rating"].mean().reset_index()

movies_df = movies.merge(
    movie_ratings,
    on="movieId"
)

# Extract year

movies_df["year"] = movies_df[
    "title"
].str.extract(r"\((\d{4})\)")

movies_df["year"] = pd.to_numeric(
    movies_df["year"],
    errors="coerce"
)

movie_tags = tags.groupby(
    "movieId"
)["tag"].apply(
    lambda x: " ".join(
        x.astype(str)
    )
).reset_index()

movies_nlp = movies_df.merge(
    movie_tags,
    on="movieId",
    how="left"
)

movies_nlp["tag"] = movies_nlp[
    "tag"
].fillna("")

movies_nlp["text"] = (
    movies_nlp["genres"]
    + " "
    + movies_nlp["tag"]
)

tfidf = TfidfVectorizer(
    stop_words="english"
)

tfidf_matrix = tfidf.fit_transform(
    movies_nlp["text"]
)

st.title(
    "Hybrid Movie Recommendation System"
)

genre = st.selectbox(
    "Genre",
    [
        "Action",
        "Adventure",
        "Animation",
        "Comedy",
        "Crime",
        "Drama",
        "Fantasy",
        "Romance",
        "Sci-Fi",
        "Thriller"
    ]
)

rating = st.slider(
    "Minimum Rating",
    0.0,
    5.0,
    4.0
)

year = st.slider(
    "Minimum Year",
    1950,
    2025,
    2000
)

query = st.text_input(
    "Describe a movie",
    "family animation"
)

if st.button("Recommend Movies"):

    query_vector = tfidf.transform(
        [query]
    )

    similarity_scores = cosine_similarity(
        query_vector,
        tfidf_matrix
    ).flatten()

    movies_nlp[
        "similarity_score"
    ] = similarity_scores

    results = movies_nlp[
        (movies_nlp["genres"].str.contains(
            genre,
            case=False,
            na=False
        ))
        &
        (movies_nlp["rating"] >= rating)
        &
        (movies_nlp["year"] >= year)
    ]

    results = results.sort_values(
        by=[
            "similarity_score",
            "rating"
        ],
        ascending=False
    )

    st.dataframe(
        results[
            [
                "title",
                "genres",
                "rating",
                "year",
                "similarity_score"
            ]
        ].head(10)
    )

